CREATE TABLE Users (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(100) NOT NULL,
    StudentNumber NVARCHAR(50) NOT NULL,
    Course NVARCHAR(100) NOT NULL,
    Email NVARCHAR(256) NOT NULL UNIQUE,
    Password NVARCHAR(256) NOT NULL,
    Rfid NVARCHAR(50) NOT NULL
);